# src/docker-compose.yml
version: "3.9"

services:
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Nam@15112003
  #   ports:
  #     - "1432:1433"
  #   volumes:
  #     - sqlserver-data:/var/opt/mssql

  iam_api:
    build:
      context: . # src/ là gốc
      dockerfile: Services/IAM/IAM.API/Dockerfile # Từ src/
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=server=metro.proxy.rlwy.net;port=50978;database=Account;user=root;password=kKEmWFekmuZNDnIRnwxJHHZSJdlukOYW;SslMode=None;
    # depends_on:
    #   sqlserver:
    #     condition: service_healthy

  course_api:
    build:
      context: .
      dockerfile: Services/CourseManagement/CourseManagement.API/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=server=metro.proxy.rlwy.net;port=50978;database=exam_management;user=root;password=kKEmWFekmuZNDnIRnwxJHHZSJdlukOYW;SslMode=None;

  submission_api:
    build:
      context: .
      dockerfile: Services/Submission/Submission.API/Dockerfile
    ports:
      - "8083:8080"
    env_file:
      - Services/Submission/Submission.API/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=tcp:demo-db-1.database.windows.net,1433;Initial Catalog=ESGS_Submission;Persist Security Info=False;User ID=namnt;Password=Nam@15112003;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;

  api-gateway:
    build:
      context: .
      dockerfile: ApiGateways/YarnApiGateway/Dockerfile
    ports:
      - "7232:443"
      - "5103:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7232
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ../https:/https:ro # LÊN 1 cấp → ExamSubmissionGradingSystem.Microservices/https
    depends_on:
      - iam_api
      - course_api
      - submission_api

volumes:
  sqlserver-data:
